# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pages\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from HandGestureRecognition.hand_gesture_module import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 600))
        MainWindow.setMaximumSize(QtCore.QSize(900, 600))
        MainWindow.setStyleSheet("background-color: rgb(56, 58, 89);    \n"
"color: rgb(255, 255, 255);")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_instructions = QtWidgets.QWidget()
        self.page_instructions.setObjectName("page_instructions")
        self.formLayout = QtWidgets.QFormLayout(self.page_instructions)
        self.formLayout.setObjectName("formLayout")
        self.button_proceed = QtWidgets.QPushButton(self.page_instructions)
        self.button_proceed.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_proceed.setStyleSheet("background-color: rgb(0, 209, 190);\n"
"font: 75 14pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.button_proceed.setObjectName("button_proceed")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.button_proceed)
        self.label_description = QtWidgets.QLabel(self.page_instructions)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("color: rgb(98, 114, 164);")
        self.label_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_description.setWordWrap(True)
        self.label_description.setObjectName("label_description")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_description)
        self.stackedWidget.addWidget(self.page_instructions)
        self.page_capture = QtWidgets.QWidget()
        self.page_capture.setObjectName("page_capture")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_capture)
        self.gridLayout_2.setContentsMargins(15, 15, 15, 15)
        self.gridLayout_2.setSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_vidCapture = QtWidgets.QVBoxLayout()
        self.verticalLayout_vidCapture.setObjectName("verticalLayout_vidCapture")
        self.frame_vidCapture = QtWidgets.QFrame(self.page_capture)
        self.frame_vidCapture.setStyleSheet("background-color: rgb(98, 114, 164);\n"
"border-radius: 10px;")
        self.frame_vidCapture.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_vidCapture.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_vidCapture.setObjectName("frame_vidCapture")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_vidCapture)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_vidCapture = QtWidgets.QLabel(self.frame_vidCapture)
        self.label_vidCapture.setStyleSheet("border-radius: 10px;")
        self.label_vidCapture.setText("")
        self.label_vidCapture.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vidCapture.setObjectName("label_vidCapture")

        # Button Clicked
        self.button_proceed.clicked.connect(lambda: self.stackedWidget.setCurrentWidget(self.page_capture))

        # Hand Gesture Module
        self.GestureModule = HandGestureModule()
        self.GestureModule.start()
        self.GestureModule.ImageUpdate.connect(self.ImageUpdateSlot)

        self.verticalLayout.addWidget(self.label_vidCapture)
        self.verticalLayout_vidCapture.addWidget(self.frame_vidCapture)
        self.gridLayout_2.addLayout(self.verticalLayout_vidCapture, 0, 0, 1, 1)
        self.verticalLayout_info = QtWidgets.QVBoxLayout()
        self.verticalLayout_info.setObjectName("verticalLayout_info")
        self.frame_info = QtWidgets.QFrame(self.page_capture)
        self.frame_info.setStyleSheet("background-color: rgb(98, 114, 164);\n"
"border-radius: 10px;")
        self.frame_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info.setObjectName("frame_info")
        self.verticalLayout_info.addWidget(self.frame_info)
        self.gridLayout_2.addLayout(self.verticalLayout_info, 0, 1, 1, 1)
        self.verticalLayout_stats = QtWidgets.QVBoxLayout()
        self.verticalLayout_stats.setObjectName("verticalLayout_stats")
        self.frame_stats = QtWidgets.QFrame(self.page_capture)
        self.frame_stats.setStyleSheet("background-color: rgb(98, 114, 164);\n"
"border-radius: 10px;")
        self.frame_stats.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_stats.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_stats.setObjectName("frame_stats")
        self.verticalLayout_stats.addWidget(self.frame_stats)
        self.gridLayout_2.addLayout(self.verticalLayout_stats, 1, 0, 1, 2)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.gridLayout_2.setRowStretch(0, 2)
        self.gridLayout_2.setRowStretch(1, 1)
        self.stackedWidget.addWidget(self.page_capture)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project Drone Dance by Team MCS7"))
        self.button_proceed.setText(_translate("MainWindow", "CONTINUE"))
        self.label_description.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#0097c5;\">Welcome,</span></p><p><span style=\" font-size:12pt;\"><br/></span></p><p><span style=\" font-size:12pt; color:#0097c5;\">Before pressing the continue button, please make sure that you have a webcam and have already connected the drones via the router. Please see the user guide and follow the instructions carefully.</span></p><p><span style=\" font-size:12pt;\"><br/></span></p><p><span style=\" font-size:12pt; color:#0097c5;\">Thank you.</span></p></body></html>"))

    def ImageUpdateSlot(self, Frame):
        self.label_vidCapture.setPixmap(QtGui.QPixmap.fromImage(Frame))